### ISSUE TITLE
Function expressions for named components

### ISSUE THREAD

**Issue by Richienb** [xojs/eslint-config-xo-react#32]
I like defining my components in a succinct function just like how it is in the [docs](https://reactjs.org/docs/components-and-props.html#function-and-class-components):

```js
export default function Home() {
	return (
		<div>
		</div>
	);
}
```

What makes the default of arrow function components better?

```js
const Home = () => (
	<div>
	</div>
);

export default Home;
```

**Comment by sindresorhus** [comment]
Yeah, I have grown to prefer the format style too for exported functions.
